safe: true
future: true
exclude: [.gitattributes, .gitignore, flywaydb.org.iml, flywaydb.org.ipr, flywaydb.org.iws, README.md, CNAME, Gemfile, Gemfile.lock, .idea/workspace.xml]
flywayVersion: 8.0.5
markdown: kramdown
url: https://flywaydb.org
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
