safe: true
future: true
exclude: [.gitattributes, .gitignore, flywaydb.org.iml, flywaydb.org.ipr, flywaydb.org.iws, README.md, CNAME, Gemfile, Gemfile.lock, .idea/workspace.xml]
flywayVersion: 6.1.3
markdown: kramdown
url: https://flywaydb.org
kramdown:
  input: GFM
  syntax_highlighter: rouge
